package com.hillel.HW_12;

public enum ConverterType  {

    CELSIUSTOFAHRENHEIT, CELSIUSTOKELVIN, FAHRENHEITTOCELSIUS, INCHESTOMETERS, KILOGRAMSTOPOUNDS,
    KILOMETRESTOMILES, METERSTOOINCHES, MILESTOKILOMETRES, POUNDSTOKILOGRAMS, SPEEDKMTOMI, SPEEDMITOKM
}
